In [47]:
import torch
import torch.nn as nn

In [48]:
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [49]:
features = torch.rand(10,5)

model = Model(features.shape[1])
#model.forward(features)
model(features)


tensor([[0.5670],
        [0.5795],
        [0.4724],
        [0.6390],
        [0.4236],
        [0.5030],
        [0.5004],
        [0.5038],
        [0.5676],
        [0.5446]], grad_fn=<SigmoidBackward0>)

In [50]:
model.linear.weight

Parameter containing:
tensor([[ 0.2660,  0.3961,  0.3785,  0.1351, -0.4322]], requires_grad=True)

In [51]:
model.linear.bias

Parameter containing:
tensor([-0.1179], requires_grad=True)

In [52]:
 !pip install torchinfo

In [53]:
from torchinfo import summary

In [54]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [55]:
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, feature_name):
        super().__init__()

        # self.linear1 = nn.Linear(feature_name, 3)
        # self.relu = nn.ReLU()

        # self.linear2 = nn.Linear(3, 1)
        # self.sigmoid = nn.Sigmoid()
        self.network = nn.Sequential(
        nn.Linear(feature_name, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()

        )
    def forward(self, features):
        # out = self.linear1(features)
        # out = self.relu(out)

        # out = self.linear2(out)
        # out = self.sigmoid(out)
        out = self.network(features)

        return out


In [56]:
features = torch.rand(10,5)
model = Model(features.shape[1])

model

Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [57]:
model(features)

tensor([[0.5959],
        [0.5651],
        [0.6023],
        [0.6333],
        [0.5952],
        [0.6395],
        [0.6515],
        [0.6218],
        [0.6215],
        [0.6081]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear2.bias

In [59]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00